### ISSUE TITLE
Fix the black circle with the github icon, which is for some reason ever-so-slightly squished

### ISSUE THREAD

**Issue by claire-peters** [geistling/website#3]

**Comment by seabassgonzalez** [comment]
After messing with it a little, it appears to be an optical illusion created by the two-tone silhouette of the octocat and the frame-- the break in the white circle at the bottom of the figure makes the image look longer length-wise, therefore squished, or oval-like... I found this is diminished by increasing the size of the logo a bit, but further refinement possibly by messing with that and padding

**Comment by seabassgonzalez** [comment]
Fixed by #10

**Comment by claire-peters** [comment]
So inspecting it as an element showed the github circle to really be of a slightly distorted size - it was around 33.5x36, while the twitter circle is 36x36. Changing the size of the github logo changed its circle dimensions to 38.28x36. I like the look of the larger logo, frankly, but there's got to be a way to constrain the size of the background so it stays 36x36.

**Comment by seabassgonzalez** [comment]
I've got the circles constrained to 36x36, but I can't get the rendering of Font Awesome's icons to be equally sized/centered within them just yet.

**Comment by claire-peters** [comment]
Hrm. I'll try to help out and play around a bit with this as well.
